name: flash_form

packages:
  - packages/**

sdkPath: .fvm/flutter_sdk

scripts:
  analyze:
    name: analyze
    exec: dart analyze .

  clean:
    name: clean
    exec: fvm flutter clean

  repair:
    name: repair
    exec: fvm flutter pub cache repair

  fix_dry-run:
    name: fix dry-run
    exec: dart fix --dry-run .

  fix_apply:
    name: fix apply
    exec: dart fix --apply .

  pub_get:
    name: pub_get
    exec: fvm flutter pub get

  pub_upgrade:
    name: pub_upgrade
    exec: fvm flutter pub upgrade

  build_runner_watch:
    name: build_runner
    exec: fvm flutter pub run build_runner watch --delete-conflicting-outputs

  image_gen:
    name: image_gen
    exec: fluttergen -c pubspec.yaml
