import 'dart:math';

enum Country {
  USA,
  Japan,
  France,
  India,
  Germany,
  UK,
  China,
  Russia,
  Brazil,
  Canada,
  Australia,
  Italy,
  Spain,
  Mexico,
  SouthKorea
}

class Person {
  final String firstname;
  final String lastname;
  final int age;
  final List<String> hobbies;
  final Country country;

  Person({
    required this.firstname,
    required this.lastname,
    required this.age,
    required this.hobbies,
    required this.country,
  });

  String get name => '$firstname $lastname';

  @override
  String toString() {
    return 'Person(firstname: $firstname, lastname: $lastname, age: $age, hobbies: $hobbies, country: $country)';
  }
}

class PersonGenerator {
  final Random _random = Random();

  final Map<Country, List<String>> _firstnames = {
    Country.USA: [
      'John',
      'Jane',
      'Michael',
      'Emily',
      'Chris',
      'Jessica',
      'James',
      'Mary',
      'Robert',
      'Patricia',
      'David',
      'Linda',
      'William',
      'Barbara',
      'Joseph',
      'Elizabeth',
      'Thomas',
      'Jennifer',
      'Charles',
      'Maria',
      'Daniel',
      'Susan',
      'Matthew',
      'Margaret',
      'Anthony',
      'Dorothy',
      'Mark',
      'Nancy',
      'Paul',
      'Karen',
      'Steven',
      'Betty',
      'Kenneth',
      'Helen',
      'George',
      'Sandra',
      'Edward',
      'Donna',
      'Brian',
      'Carol',
      'Ronald',
      'Ruth',
      'Donald',
      'Sharon',
      'Anthony',
      'Michelle',
      'Kevin',
      'Laura',
      'Jason',
      'Sarah',
      'Jeffrey',
      'Kimberly',
      'Ryan',
      'Deborah',
      'Jacob',
      'Jessica',
      'Gary',
      'Rebecca',
      'Nicholas',
      'Stephanie',
      'Eric',
      'Kathleen',
      'Stephen',
      'Emma',
      'Andrew',
      'Carolyn',
      'Joshua',
      'Christine',
      'Frank',
      'Marie',
      'Larry',
      'Janet',
      'Scott',
      'Catherine',
      'Brandon',
      'Joan',
      'Benjamin',
      'Martha',
      'Samuel',
      'Ashley',
      'Gregory',
      'Julia',
      'Raymond',
      'Hannah',
      'Patrick',
      'Angela',
      'Jack',
      'Madison',
      'Alexander',
      'Olivia',
      'Henry',
      'Samantha',
      'Dennis',
      'Grace',
      'Walter',
      'Sophia',
      'Peter',
      'Isabella'
    ],
    Country.Japan: [
      'Haruto',
      'Yui',
      'Sota',
      'Aoi',
      'Ren',
      'Hina',
      'Yuki',
      'Sakura',
      'Kaito',
      'Miyu',
      'Ryuto',
      'Hana',
      'Riku',
      'Ichika',
      'Takumi',
      'Mei',
      'Shota',
      'Mao',
      'Yuuto',
      'Sara',
      'Minato',
      'Yuna',
      'Haruki',
      'Ami',
      'Itsuki',
      'Riko',
      'Hinata',
      'Rin',
      'Koki',
      'Nanami',
      'Sho',
      'Rina',
      'Toma',
      'Miu',
      'Sora',
      'Akari',
      'Tsubasa',
      'Ayaka',
      'Yuto',
      'Mika',
      'Hinako',
      'Fuka',
      'Shinnosuke',
      'Himari',
      'Kosei',
      'Natsuki',
      'Haruna',
      'Aika',
      'Kei',
      'Misaki',
      'Ayumu',
      'Moe',
      'Hayato',
      'Yuzuki',
      'Hiroto',
      'Hinako',
      'Takuya',
      'Rin',
      'Yuji',
      'Maho',
      'Taiga',
      'Sana',
      'Ryota',
      'Ayane',
      'Shin',
      'Rino',
      'Toru',
      'Ema',
      'Sota',
      'Sakura',
      'Ren',
      'Riko',
      'Shoma',
      'Himari',
      'Rei',
      'Reina',
      'Nao',
      'Nozomi',
      'Kota',
      'Rena',
      'Seiya',
      'Honoka',
      'Haruma',
      'Manaka',
      'Yuma',
      'Yui',
      'Kazuya',
      'Yuri',
      'Eito',
      'Airi',
      'Shu',
      'Sayaka',
      'Riku',
      'Yuka',
      'Hiroki',
      'Miki'
    ],
    Country.France: [
      'Louis',
      'Emma',
      'Gabriel',
      'Chloe',
      'Hugo',
      'Alice',
      'Arthur',
      'Jade',
      'Leo',
      'Louise',
      'Lucas',
      'Manon',
      'Nathan',
      'Camille',
      'Ethan',
      'Sarah',
      'Thomas',
      'Lina',
      'Martin',
      'Eva',
      'Mathis',
      'Lea',
      'Nolan',
      'Anna',
      'Victor',
      'Zoe',
      'Enzo',
      'Julie',
      'Raphael',
      'Clara',
      'Paul',
      'Lola',
      'Axel',
      'Nina',
      'Jules',
      'Elena',
      'Maxime',
      'Romane',
      'Clement',
      'Charlotte',
      'Bastien',
      'Ambre',
      'Antoine',
      'Mila',
      'Maxence',
      'Anais',
      'Theo',
      'Lucie',
      'Noah',
      'Marie',
      'Alexandre',
      'Lou',
      'Florian',
      'Margaux',
      'Robin',
      'Jeanne',
      'Valentin',
      'Victoire',
      'Evan',
      'Lila',
      'Benjamin',
      'Maelys',
      'Adrien',
      'Amandine',
      'Julien',
      'Oceane',
      'Dylan',
      'Pauline',
      'Tom',
      'Sophie',
      'Kevin',
      'Elsa',
      'Matteo',
      'Anaelle',
      'Cedric',
      'Alicia',
      'Quentin',
      'Helene',
      'Fabien',
      'Estelle',
      'Samuel',
      'Adeline',
      'Jeremy',
      'Clarisse',
      'Anthony',
      'Claudia',
      'Pierre',
      'Lucille',
      'Yanis',
      'Violette',
      'Romain',
      'Mathilde',
      'Stephane',
      'Marion',
      'Olivier',
      'Melanie'
    ],
    Country.India: [
      'Aarav',
      'Ananya',
      'Vivaan',
      'Diya',
      'Aditya',
      'Priya',
      'Rahul',
      'Pooja',
      'Arjun',
      'Kavya',
      'Karan',
      'Isha',
      'Rohan',
      'Neha',
      'Ayaan',
      'Riya',
      'Dev',
      'Shreya',
      'Aryan',
      'Nisha',
      'Kabir',
      'Saanvi',
      'Ishaan',
      'Tara',
      'Krishna',
      'Anika',
      'Raghav',
      'Kriti',
      'Yash',
      'Pari',
      'Rudra',
      'Anvi',
      'Atharv',
      'Aarohi',
      'Om',
      'Ishika',
      'Shiv',
      'Navya',
      'Ritik',
      'Advika',
      'Veer',
      'Aadhya',
      'Rishi',
      'Jiya',
      'Arnav',
      'Meera',
      'Nirvaan',
      'Kashvi',
      'Tejas',
      'Shruti',
      'Daksh',
      'Aaradhya',
      'Ayush',
      'Akshara',
      'Nikhil',
      'Samaira',
      'Darsh',
      'Anushka',
      'Reyansh',
      'Myra',
      'Manan',
      'Diya',
      'Sai',
      'Sahana',
      'Samar',
      'Anvi',
      'Krish',
      'Mahi',
      'Pranav',
      'Riddhi',
      'Abhay',
      'Suhana',
      'Rudraksh',
      'Vaishnavi',
      'Nakul',
      'Sia',
      'Avi',
      'Nayantara',
      'Siddharth',
      'Anaya',
      'Tanmay',
      'Keya',
      'Kush',
      'Tanvi',
      'Raghavendra',
      'Anjali',
      'Advait',
      'Prisha',
      'Tushar',
      'Aradhya',
      'Samarth',
      'Anita',
      'Aarush',
      'Anushree',
      'Kunal',
      'Ira'
    ],
    Country.Germany: [
      'Lukas',
      'Mia',
      'Leon',
      'Hannah',
      'Finn',
      'Sophia',
      'Felix',
      'Lina',
      'Elias',
      'Lea',
      'Paul',
      'Emilia',
      'Jonas',
      'Lena',
      'Maximilian',
      'Marie',
      'Tim',
      'Anna',
      'Noah',
      'Laura',
      'Philipp',
      'Ella',
      'Ben',
      'Emilie',
      'David',
      'Lilly',
      'Julian',
      'Nele',
      'Jan',
      'Amelie',
      'Henry',
      'Leonie',
      'Tom',
      'Lara',
      'Moritz',
      'Clara',
      'Jakob',
      'Emma',
      'Erik',
      'Mila',
      'Niklas',
      'Zoe',
      'Samuel',
      'Luisa',
      'Dominic',
      'Fiona',
      'Fabian',
      'Sarah',
      'Sebastian',
      'Nora',
      'Alexander',
      'Johanna',
      'Tobias',
      'Maja',
      'Matthias',
      'Elena',
      'Daniel',
      'Mira',
      'Adrian',
      'Sophie',
      'Florian',
      'Paula',
      'Lars',
      'Julia',
      'Simon',
      'Lilli',
      'Jannik',
      'Jana',
      'Theo',
      'Isabel',
      'Max',
      'Alina',
      'Anton',
      'Helena',
      'Marius',
      'Martha',
      'Jonathan',
      'Celine',
      'Vincent',
      'Isabella',
      'Robert',
      'Victoria',
      'Leonard',
      'Luise',
      'Christian',
      'Ronja',
      'Marco',
      'Sina',
      'Oliver',
      'Lisa',
      'Joshua',
      'Ella',
      'Marvin',
      'Amalia',
      'Leon',
      'Franz'
    ],
    Country.UK: [
      'Oliver',
      'Olivia',
      'George',
      'Isla',
      'Harry',
      'Ava',
      'Jack',
      'Emily',
      'Charlie',
      'Sophia',
      'Jacob',
      'Grace',
      'Freddie',
      'Amelia',
      'Alfie',
      'Mia',
      'Archie',
      'Evie',
      'Oscar',
      'Ella',
      'Henry',
      'Lily',
      'Thomas',
      'Poppy',
      'Leo',
      'Daisy',
      'James',
      'Chloe',
      'William',
      'Jessica',
      'Joshua',
      'Alice',
      'Logan',
      'Sophie',
      'Ethan',
      'Rosie',
      'Joseph',
      'Holly',
      'Reuben',
      'Evie',
      'Lucas',
      'Zoe',
      'Samuel',
      'Ruby',
      'Harrison',
      'Florence',
      'Sebastian',
      'Ivy',
      'Max',
      'Sienna',
      'Daniel',
      'Willow',
      'Isaac',
      'Elsie',
      'Adam',
      'Layla',
      'Alexander',
      'Matilda',
      'Dylan',
      'Harriet',
      'Edward',
      'Mila',
      'Benjamin',
      'Emilia',
      'Theodore',
      'Luna',
      'Matthew',
      'Ellie',
      'Luke',
      'Aurora',
      'Toby',
      'Erin',
      'Jayden',
      'Eliza',
      'Nathan',
      'Molly',
      'Finn',
      'Darcie',
      'Jake',
      'Francesca',
      'Hugo',
      'Amber',
      'Cameron',
      'Lottie',
      'Michael',
      'Nancy',
      'David',
      'Violet',
      'Louis',
      'Annabelle',
      'Elijah',
      'Bella',
      'Gabriel',
      'Olive',
      'Liam',
      'Penny'
    ],
    Country.China: [
      'Wei',
      'Mei',
      'Jian',
      'Li',
      'Hao',
      'Fen',
      'Ping',
      'Lian',
      'Yun',
      'Ming',
      'Xiao',
      'Lan',
      'Tao',
      'Fang',
      'Zhen',
      'Shu',
      'Jing',
      'Qing',
      'Ting',
      'Qian',
      'Yang',
      'Hui',
      'Chao',
      'Xue',
      'Lei',
      'Bo',
      'Ling',
      'Hong',
      'Yi',
      'Nan',
      'Zhao',
      'Zhou',
      'Wang',
      'Chen',
      'Zhang',
      'Liu',
      'Yang',
      'Huang',
      'Zhu',
      'Cao',
      'Lu',
      'Deng',
      'Pan',
      'Yuan',
      'Gao',
      'Zheng',
      'Xu',
      'Sun',
      'Guo',
      'Luo',
      'Yu',
      'Qiu',
      'Ma',
      'Gong',
      'Qin',
      'Dong',
      'Wen',
      'Wu',
      'Yan',
      'Fan',
      'Xiong',
      'Chang',
      'Bao',
      'Tian',
      'Kang',
      'Lai',
      'Mo',
      'Xia',
      'Luo',
      'Cai',
      'Peng',
      'He',
      'Luo',
      'Song',
      'Shen',
      'Zong',
      'Cao',
      'Ren',
      'Kong',
      'Liang',
      'Li',
      'Yuan',
      'Lu',
      'Xiao',
      'Wang',
      'Zheng',
      'Sun',
      'Hu',
      'Mao',
      'Yuan',
      'Zhou',
      'Qi',
      'Tang',
      'Guo',
      'Cai',
      'Wei',
      'Fan',
      'Yue',
      'Jiang',
      'Gao'
    ],
    Country.Russia: [
      'Alexander',
      'Anastasia',
      'Dmitry',
      'Maria',
      'Ivan',
      'Ekaterina',
      'Sergey',
      'Olga',
      'Nikolay',
      'Natalia',
      'Vladimir',
      'Svetlana',
      'Andrey',
      'Tatiana',
      'Yuri',
      'Elena',
      'Maxim',
      'Irina',
      'Alexey',
      'Marina',
      'Mikhail',
      'Galina',
      'Nikolai',
      'Valentina',
      'Pavel',
      'Veronika',
      'Denis',
      'Lyudmila',
      'Kirill',
      'Polina',
      'Yaroslav',
      'Evgeniya',
      'Roman',
      'Nadezhda',
      'Konstantin',
      'Liliya',
      'Artem',
      'Larisa',
      'Viktor',
      'Diana',
      'Stanislav',
      'Alina',
      'Oleg',
      'Sofia',
      'Igor',
      'Anna',
      'Vladislav',
      'Elizaveta',
      'Gleb',
      'Yulia',
      'Fyodor',
      'Arina',
      'Stepan',
      'Taisiya',
      'Timofey',
      'Kseniya',
      'Yevgeny',
      'Inna',
      'Bogdan',
      'Raisa',
      'Anton',
      'Valeriya',
      'Boris',
      'Zoya',
      'Ilya',
      'Natalya',
      'Georgiy',
      'Lidia',
      'Daniil',
      'Oksana',
      'Rostislav',
      'Tamara',
      'Vyacheslav',
      'Mila',
      'Igor',
      'Vera',
      'Vasily',
      'Margarita',
      'Leonid',
      'Alla',
      'German',
      'Zinaida',
      'Daniil',
      'Anfisa',
      'Semyon',
      'Ulyana',
      'Vsevolod',
      'Alena',
      'Rodion',
      'Karina',
      'Yakov',
      'Vasilisa',
      'Platon',
      'Yana',
      'Danila',
      'Zina',
      'Maksim',
      'Taisia',
      'Viktoria',
      'Sofya'
    ],
    Country.Brazil: [
      'Miguel',
      'Alice',
      'Arthur',
      'Laura',
      'Gabriel',
      'Valentina',
      'Heitor',
      'Sophia',
      'Bernardo',
      'Isabella',
      'Davi',
      'Helena',
      'Lorenzo',
      'Manuela',
      'Théo',
      'Júlia',
      'Pedro',
      'Luiza',
      'Benjamin',
      'Beatriz',
      'Matheus',
      'Maria',
      'Lucas',
      'Ana',
      'Nicolas',
      'Gabriela',
      'Guilherme',
      'Maitê',
      'Rafael',
      'Larissa',
      'Felipe',
      'Melissa',
      'Gustavo',
      'Yasmin',
      'Enzo',
      'Emanuelly',
      'Henrique',
      'Isadora',
      'Joaquim',
      'Mariah',
      'João',
      'Letícia',
      'Eduardo',
      'Nicole',
      'Samuel',
      'Rebeca',
      'Cauã',
      'Rafaela',
      'Emanuel',
      'Lavínia',
      'Caleb',
      'Eloá',
      'Daniel',
      'Livia',
      'Benjamin',
      'Mirella',
      'Bryan',
      'Ana',
      'Anthony',
      'Esther',
      'Rodrigo',
      'Bárbara',
      'Bruno',
      'Aline',
      'Igor',
      'Mariana',
      'Renan',
      'Luciana',
      'Thiago',
      'Elisa',
      'Juan',
      'Catarina',
      'Leandro',
      'Clarice',
      'Vinícius',
      'Maysa',
      'Frederico',
      'Ana',
      'Fernando',
      'Isabel',
      'Márcio',
      'Eduarda',
      'Wesley',
      'Alice',
      'Otávio',
      'Cristina',
      'Paulo',
      'Cecília',
      'André',
      'Luana',
      'Elias',
      'Nathalia',
      'Ronaldo',
      'Raquel',
      'Fábio',
      'Carolina'
    ],
    Country.Canada: [
      'Liam',
      'Emma',
      'Noah',
      'Charlotte',
      'Lucas',
      'Avery',
      'Mason',
      'Amelia',
      'Ethan',
      'Harper',
      'James',
      'Ella',
      'Benjamin',
      'Abigail',
      'Logan',
      'Emily',
      'Jackson',
      'Sofia',
      'Sebastian',
      'Mia',
      'Alexander',
      'Aria',
      'Jacob',
      'Scarlett',
      'Aiden',
      'Elizabeth',
      'Owen',
      'Chloe',
      'Henry',
      'Isla',
      'Samuel',
      'Nora',
      'Matthew',
      'Grace',
      'Nathan',
      'Layla',
      'Elijah',
      'Lily',
      'Carter',
      'Hannah',
      'Daniel',
      'Addison',
      'William',
      'Zoe',
      'Luke',
      'Samantha',
      'Dylan',
      'Mila',
      'Leo',
      'Paisley',
      'Isaac',
      'Hazel',
      'David',
      'Eva',
      'Caleb',
      'Ellie',
      'Ryan',
      'Victoria',
      'Wyatt',
      'Riley',
      'Gabriel',
      'Lucy',
      'Jayden',
      'Aubrey',
      'John',
      'Penelope',
      'Connor',
      'Aurora',
      'Isaiah',
      'Nova',
      'Jack',
      'Sadie',
      'Lincoln',
      'Natalie',
      'Joshua',
      'Willow',
      'Grayson',
      'Madison',
      'Hunter',
      'Stella',
      'Eli',
      'Leah',
      'Christian',
      'Luna',
      'Aaron',
      'Violet',
      'Jonathan',
      'Savannah',
      'Thomas',
      'Brooklyn',
      'Charles',
      'Claire',
      'Josiah',
      'Ariana',
      'Andrew',
      'Skylar'
    ],
    Country.Australia: [
      'Jack',
      'Charlotte',
      'William',
      'Olivia',
      'James',
      'Mia',
      'Thomas',
      'Ava',
      'Lucas',
      'Zoe',
      'Henry',
      'Isabella',
      'Leo',
      'Grace',
      'Alexander',
      'Amelia',
      'Mason',
      'Sophie',
      'Liam',
      'Harper',
      'Ethan',
      'Ruby',
      'Noah',
      'Chloe',
      'Isaac',
      'Willow',
      'Samuel',
      'Emily',
      'Oscar',
      'Lily',
      'Benjamin',
      'Ella',
      'Harrison',
      'Evie',
      'Joshua',
      'Matilda',
      'Hunter',
      'Lucy',
      'Logan',
      'Mila',
      'Michael',
      'Poppy',
      'Elijah',
      'Scarlett',
      'Jacob',
      'Ivy',
      'Daniel',
      'Aria',
      'Harry',
      'Abigail',
      'Adam',
      'Isla',
      'Andrew',
      'Alice',
      'Matthew',
      'Hazel',
      'Sebastian',
      'Sienna',
      'Ryan',
      'Hannah',
      'Nathan',
      'Maddison',
      'Owen',
      'Evelyn',
      'Christian',
      'Audrey',
      'Gabriel',
      'Sophia',
      'Luke',
      'Ellie',
      'Nicholas',
      'Imogen',
      'Charles',
      'Zara',
      'Jaxon',
      'Violet',
      'David',
      'Georgia',
      'Jayden',
      'Stella',
      'Joseph',
      'Annabelle',
      'Lincoln',
      'Luna',
      'Lachlan',
      'Alyssa',
      'Aaron',
      'Rose',
      'Connor',
      'Sarah',
      'Angus',
      'Maya',
      'Hudson',
      'Mackenzie',
      'Zachary',
      'Piper'
    ],
    Country.Italy: [
      'Lorenzo',
      'Sofia',
      'Francesco',
      'Giulia',
      'Alessandro',
      'Aurora',
      'Leonardo',
      'Alice',
      'Mattia',
      'Ginevra',
      'Tommaso',
      'Martina',
      'Gabriele',
      'Emma',
      'Riccardo',
      'Anna',
      'Edoardo',
      'Chiara',
      'Matteo',
      'Beatrice',
      'Andrea',
      'Viola',
      'Giovanni',
      'Sara',
      'Pietro',
      'Greta',
      'Federico',
      'Valentina',
      'Nicolo',
      'Francesca',
      'Antonio',
      'Gaia',
      'Matias',
      'Elena',
      'Christian',
      'Isabel',
      'Marco',
      'Miriam',
      'Samuele',
      'Giada',
      'Diego',
      'Giorgia',
      'Luca',
      'Clara',
      'Raffaele',
      'Mia',
      'Manuel',
      'Sabrina',
      'Simone',
      'Rosa',
      'Angelo',
      'Alessia',
      'Roberto',
      'Giorgio',
      'Jacopo',
      'Giovanna',
      'Stefano',
      'Angelica',
      'Vincenzo',
      'Giuliano',
      'Alberto',
      'Cristina',
      'Claudio',
      'Vanessa',
      'Michele',
      'Elisa',
      'Giacomo',
      'Silvia',
      'Vittorio',
      'Patrizia',
      'Massimo',
      'Federica',
      'Daniele',
      'Paola',
      'Luciano',
      'Margherita',
      'Tiziano',
      'Daniela',
      'Sandro',
      'Barbara',
      'Enrico',
      'Gloria',
      'Filippo',
      'Caterina',
      'Gino',
      'Gabriella',
      'Valerio',
      'Veronica',
      'Lorenza',
      'Antonella',
      'Salvatore',
      'Monica',
      'Marcello',
      'Rita',
      'Emilio',
      'Carla'
    ],
    Country.Spain: [
      'Hugo',
      'Lucia',
      'Mateo',
      'Sofia',
      'Martin',
      'Martina',
      'Lucas',
      'Maria',
      'Leo',
      'Julia',
      'Daniel',
      'Paula',
      'Alejandro',
      'Valeria',
      'Pablo',
      'Alba',
      'Manuel',
      'Noa',
      'Adrian',
      'Carmen',
      'Alvaro',
      'Daniela',
      'David',
      'Vega',
      'Mario',
      'Carla',
      'Enzo',
      'Sara',
      'Diego',
      'Mia',
      'Marcos',
      'Aitana',
      'Thiago',
      'Claudia',
      'Javier',
      'Olivia',
      'Marco',
      'Marta',
      'Alex',
      'Emma',
      'Bruno',
      'Alejandra',
      'Oliver',
      'Lara',
      'Miguel',
      'Jimena',
      'Antonio',
      'Alicia',
      'Juan',
      'Ariadna',
      'Gonzalo',
      'Vera',
      'Gael',
      'Elena',
      'Sergio',
      'Irene',
      'Nicolas',
      'Nerea',
      'Ivan',
      'Angela',
      'Jesus',
      'Ines',
      'Carlos',
      'Blanca',
      'Raul',
      'Victoria',
      'Jorge',
      'Marina',
      'Santiago',
      'Candela',
      'Izan',
      'Lola',
      'Ruben',
      'Ana',
      'Samuel',
      'Clara',
      'Rafael',
      'Ainhoa',
      'Fernando',
      'Elsa',
      'Hector',
      'Laura',
      'Amir',
      'Laia',
      'Erik',
      'Adriana',
      'Rodrigo',
      'Manuela',
      'Victor',
      'Leyre',
      'Saul',
      'Elia',
      'Mohamed',
      'Mara',
      'Francisco',
      'Nuria'
    ],
    Country.Mexico: [
      'Santiago',
      'Valentina',
      'Sebastian',
      'Regina',
      'Mateo',
      'Ximena',
      'Leonardo',
      'Victoria',
      'Matias',
      'Camila',
      'Emiliano',
      'Maria',
      'Diego',
      'Fernanda',
      'Daniel',
      'Sofia',
      'Miguel',
      'Valeria',
      'Alejandro',
      'Andrea',
      'Javier',
      'Natalia',
      'Carlos',
      'Gabriela',
      'Emmanuel',
      'Renata',
      'Gabriel',
      'Mariana',
      'Eduardo',
      'Romina',
      'Samuel',
      'Luciana',
      'David',
      'Ivanna',
      'Emilio',
      'Mia',
      'Angel',
      'Alexa',
      'Jose',
      'Julia',
      'Andres',
      'Abigail',
      'Juan',
      'Ana',
      'Luis',
      'Miranda',
      'Pablo',
      'Paola',
      'Rodrigo',
      'Allison',
      'Jorge',
      'Carolina',
      'Ricardo',
      'Adriana',
      'Fernando',
      'Abril',
      'Aaron',
      'Valery',
      'Rafael',
      'Fabiola',
      'Manuel',
      'Elena',
      'Ivan',
      'Zoe',
      'Martin',
      'Claudia',
      'Raul',
      'Cecilia',
      'Hector',
      'Isabella',
      'Marcos',
      'Danna',
      'Cesar',
      'Montserrat',
      'Antonio',
      'Liliana',
      'Mario',
      'Angeles',
      'Alexis',
      'Fabiana',
      'Francisco',
      'Berenice',
      'Armando',
      'Luz',
      'Enrique',
      'Sara',
      'Jesus',
      'Patricia',
      'Raul',
      'Erika',
      'Esteban',
      'Silvia',
      'Mariano',
      'Norma',
      'Adrian',
      'Ariadna'
    ],
    Country.SouthKorea: [
      'Seo-jun',
      'Seo-yeon',
      'Ji-ho',
      'Ha-eun',
      'Do-yun',
      'Ji-min',
      'Min-jun',
      'Soo-ah',
      'Joon-woo',
      'Seo-hyun',
      'Ha-joon',
      'Jin-woo',
      'Yu-na',
      'Jae-won',
      'Hyun-woo',
      'Ji-an',
      'Tae-yang',
      'Min-seo',
      'Gun-woo',
      'Yeon-woo',
      'Seung-woo',
      'Ji-woo',
      'Ji-hoon',
      'Min-ji',
      'Joo-won',
      'Yeo-jin',
      'Dong-hyun',
      'Na-eun',
      'Sung-ho',
      'Jin-young',
      'Jung-hoon',
      'Bo-ram',
      'Kang-min',
      'Ha-rin',
      'Hyeon-seo',
      'Eun-ji',
      'Chan-ho',
      'Hee-jin',
      'In-ho',
      'Seon-hwa',
      'Sang-hoon',
      'Chae-won',
      'Ji-won',
      'Hye-jin',
      'Young-jun',
      'Sun-young',
      'Yoon-seo',
      'Jin-sook',
      'Jong-hyun',
      'Hye-won',
      'Yoon-hee',
      'Dong-wook',
      'Yun-jin',
      'Seung-min',
      'Ji-eun',
      'Seok-jin',
      'Ji-hye',
      'Min-hyuk',
      'Hyeon-jin',
      'Ye-jin',
      'Kyung-soo',
      'Jung-min',
      'Hyun-sook',
      'Min-woo',
      'Sun-hee',
      'Jun-seo',
      'Hye-jin',
      'Jun-ho',
      'Yeon-joo',
      'Dong-min',
      'Jung-woo',
      'Ha-young',
      'Jong-seo',
      'Soo-jin',
      'Joon-seo',
      'Hye-seon',
      'Young-woo',
      'Ji-hyun',
      'Yun-ho',
      'Min-joo',
      'Ji-hun',
      'Hee-sun',
      'Chan-wook',
      'Seul-ki',
      'Jun-young',
      'Hye-soo',
      'Sung-min',
      'Hye-seo',
      'Woo-jin',
      'Ji-yeon',
      'Soo-yeon',
      'Eun-young',
      'Jong-hwa',
      'So-eun',
      'Ji-sung',
      'Hee-young'
    ]
  };

  final Map<Country, List<String>> _lastnames = {
    Country.USA: [
      'Smith',
      'Johnson',
      'Williams',
      'Brown',
      'Jones',
      'Garcia',
      'Miller',
      'Davis',
      'Martinez',
      'Hernandez',
      'Lopez',
      'Gonzalez',
      'Wilson',
      'Anderson',
      'Thomas',
      'Taylor',
      'Moore',
      'Jackson',
      'Martin',
      'Lee',
      'Perez',
      'Thompson',
      'White',
      'Harris',
      'Sanchez',
      'Clark',
      'Ramirez',
      'Lewis',
      'Robinson',
      'Walker',
      'Young',
      'Allen',
      'King',
      'Wright',
      'Scott',
      'Torres',
      'Nguyen',
      'Hill',
      'Flores',
      'Green',
      'Adams',
      'Nelson',
      'Baker',
      'Hall',
      'Rivera',
      'Campbell',
      'Mitchell',
      'Carter',
      'Roberts',
      'Gomez',
      'Phillips',
      'Evans',
      'Turner',
      'Diaz',
      'Parker',
      'Cruz',
      'Edwards',
      'Collins',
      'Reyes',
      'Stewart',
      'Morris',
      'Morales',
      'Murphy',
      'Cook',
      'Rogers',
      'Gutierrez',
      'Ortiz',
      'Morgan',
      'Cooper',
      'Peterson',
      'Bailey',
      'Reed',
      'Kelly',
      'Howard',
      'Ramos',
      'Kim',
      'Cox',
      'Ward',
      'Richardson',
      'Watson',
      'Brooks',
      'Chavez',
      'Wood',
      'James',
      'Bennett',
      'Gray',
      'Mendoza',
      'Ruiz',
      'Hughes',
      'Price',
      'Alvarez',
      'Castillo',
      'Sanders',
      'Patel',
      'Myers',
      'Long'
    ],
    Country.Japan: [
      'Sato',
      'Suzuki',
      'Takahashi',
      'Tanaka',
      'Watanabe',
      'Ito',
      'Yamamoto',
      'Nakamura',
      'Kobayashi',
      'Kato',
      'Yoshida',
      'Yamada',
      'Sasaki',
      'Yamaguchi',
      'Matsumoto',
      'Inoue',
      'Kimura',
      'Hayashi',
      'Shimizu',
      'Mori',
      'Abe',
      'Ikeda',
      'Hashimoto',
      'Yamashita',
      'Ishikawa',
      'Ogawa',
      'Ishii',
      'Hasegawa',
      'Goto',
      'Okada',
      'Kondo',
      'Fujita',
      'Murakami',
      'Ota',
      'Saito',
      'Endo',
      'Miyazaki',
      'Fukuda',
      'Nishimura',
      'Sakamoto',
      'Ishida',
      'Maeda',
      'Harada',
      'Kojima',
      'Wada',
      'Takagi',
      'Nakajima',
      'Takeuchi',
      'Kaneko',
      'Ueda',
      'Sugiyama',
      'Fujii',
      'Fukushima',
      'Fujimoto',
      'Sugawara',
      'Matsuda',
      'Nakano',
      'Matsui',
      'Miyamoto',
      'Uchida',
      'Ando',
      'Kudo',
      'Shibata',
      'Ozawa',
      'Kinoshita',
      'Maruyama',
      'Takada',
      'Shimada',
      'Morita',
      'Ichikawa',
      'Taniguchi',
      'Kawai',
      'Toyoda',
      'Kikuchi',
      'Mizuno',
      'Yasuda',
      'Takeda',
      'Kuroda',
      'Miyashita',
      'Hirata',
      'Hirano',
      'Kawaguchi',
      'Kuwabara',
      'Sakurai',
      'Hirano',
      'Ogata',
      'Tsuchiya',
      'Miyata',
      'Noguchi',
      'Takano',
      'Shinohara',
      'Matsuoka',
      'Okamoto',
      'Hara',
      'Takizawa',
      'Ogino',
      'Sakaguchi',
      'Shimizu',
      'Ueno',
      'Murai'
    ],
    Country.France: [
      'Martin',
      'Bernard',
      'Thomas',
      'Petit',
      'Robert',
      'Richard',
      'Durand',
      'Dubois',
      'Moreau',
      'Laurent',
      'Simon',
      'Michel',
      'Lefevre',
      'Leroy',
      'Roux',
      'David',
      'Bertrand',
      'Morel',
      'Fournier',
      'Girard',
      'Bonnet',
      'Dupont',
      'Lambert',
      'Fontaine',
      'Rousseau',
      'Vincent',
      'Muller',
      'Lefevre',
      'Faure',
      'Andre',
      'Mercier',
      'Blanc',
      'Guerin',
      'Boyer',
      'Garnier',
      'Chevalier',
      'Francois',
      'Legrand',
      'Gauthier',
      'Garcia',
      'Perrin',
      'Robin',
      'Clement',
      'Morin',
      'Nicolas',
      'Henry',
      'Roussel',
      'Mathieu',
      'Gautier',
      'Masson',
      'Marchand',
      'Duval',
      'Denis',
      'Dumont',
      'Marie',
      'Lemoine',
      'Lefebvre',
      'Ferreira',
      'Barbier',
      'Jacquet',
      'Lemoine',
      'Marty',
      'Renard',
      'Renaud',
      'Colin',
      'Boucher',
      'Chevallier',
      'Lucas',
      'Lambert',
      'Paul',
      'Perez',
      'Gonzalez',
      'Blanchard',
      'David',
      'Roussel',
      'Guillot',
      'Maillard',
      'Perrier',
      'Lemoine',
      'Maury',
      'Riviere',
      'Rousset',
      'Gomez',
      'Masson',
      'Dupuis',
      'Marechal',
      'Fournier',
      'Delaunay',
      'Aubert',
      'Jacques',
      'Poisson',
      'Labbe',
      'Jacquet',
      'Verdier',
      'Gros',
      'Chartier'
    ],
    Country.India: [
      'Singh',
      'Kumar',
      'Sharma',
      'Patel',
      'Mishra',
      'Reddy',
      'Chowdhury',
      'Nair',
      'Gupta',
      'Mehta',
      'Joshi',
      'Das',
      'Rao',
      'Sinha',
      'Agarwal',
      'Pandey',
      'Shah',
      'Roy',
      'Verma',
      'Bhat',
      'Chaudhary',
      'Kapoor',
      'Jain',
      'Yadav',
      'Rana',
      'Dutta',
      'Ghosh',
      'Khan',
      'Saxena',
      'Mannan',
      'Kashyap',
      'Iyer',
      'Garg',
      'Bhattacharya',
      'Singhania',
      'Basu',
      'Raman',
      'Chakraborty',
      'Dasgupta',
      'Dey',
      'Kulkarni',
      'Menon',
      'Nambiar',
      'Narayan',
      'Pal',
      'Pathak',
      'Raghavan',
      'Sengupta',
      'Srivastava',
      'Swaminathan',
      'Subramanian',
      'Banerjee',
      'Basu',
      'Chakrabarti',
      'Chakraborty',
      'Chatterjee',
      'Chaudhuri',
      'Datta',
      'De',
      'Desai',
      'Dutta',
      'Ganguly',
      'Ghoshal',
      'Gokhale',
      'Goswami',
      'Iyer',
      'Joshi',
      'Kashyap',
      'Khatri',
      'Kohli',
      'Lal',
      'Mehta',
      'Mitra',
      'Mohan',
      'Mukherjee',
      'Muralidharan',
      'Nanda',
      'Narayanan',
      'Pandit',
      'Prasad',
      'Raj',
      'Rao',
      'Reddy',
      'Saha',
      'Sarma',
      'Sen',
      'Seth',
      'Shah',
      'Srinivasan',
      'Talwar'
    ],
    Country.Germany: [
      'Müller',
      'Schmidt',
      'Schneider',
      'Fischer',
      'Weber',
      'Meyer',
      'Wagner',
      'Becker',
      'Schulz',
      'Hoffmann',
      'Koch',
      'Bauer',
      'Richter',
      'Klein',
      'Wolf',
      'Schröder',
      'Neumann',
      'Schwarz',
      'Zimmermann',
      'Braun',
      'Krüger',
      'Hofmann',
      'Hartmann',
      'Lange',
      'Schmitt',
      'Werner',
      'Schmitz',
      'Krause',
      'Meier',
      'Lehmann',
      'Schmid',
      'Schulze',
      'Maier',
      'Köhler',
      'Herrmann',
      'Walter',
      'König',
      'Mayer',
      'Huber',
      'Kaiser',
      'Fuchs',
      'Peters',
      'Lang',
      'Scholz',
      'Möller',
      'Weiß',
      'Jung',
      'Hahn',
      'Schubert',
      'Vogel',
      'Friedrich',
      'Keller',
      'Günther',
      'Frank',
      'Berger',
      'Winkler',
      'Roth',
      'Beck',
      'Lorenz',
      'Baumann',
      'Franke',
      'Albrecht',
      'Schuster',
      'Simon',
      'Ludwig',
      'Böhm',
      'Winter',
      'Kraus',
      'Martin',
      'Schumacher',
      'Krämer',
      'Vogt',
      'Stein',
      'Jäger',
      'Otto',
      'Sommer',
      'Groß',
      'Seidel',
      'Heinrich',
      'Brandt',
      'Haas',
      'Dietrich',
      'Ziegler',
      'Kuhn',
      'Pohl',
      'Engel',
      'Horn',
      'Busch',
      'Bergmann',
      'Thomas',
      'Voigt',
      'Sauer',
      'Arnold',
      'Wolff',
      'Bock',
      'Ullrich'
    ],
    Country.UK: [
      'Smith',
      'Jones',
      'Taylor',
      'Brown',
      'Williams',
      'Wilson',
      'Johnson',
      'Davies',
      'Robinson',
      'Wright',
      'Walker',
      'Thompson',
      'White',
      'Edwards',
      'Hughes',
      'Green',
      'Hall',
      'Lewis',
      'Harris',
      'Clarke',
      'Patel',
      'Jackson',
      'Wood',
      'Turner',
      'Martin',
      'Cooper',
      'Hill',
      'Ward',
      'Moore',
      'Clark',
      'Lee',
      'King',
      'Baker',
      'Harrison',
      'Morgan',
      'Allen',
      'James',
      'Scott',
      'Phillips',
      'Watson',
      'Davies',
      'Mitchell',
      'Evans',
      'Carter',
      'Morris',
      'Miller',
      'Murphy',
      'Bailey',
      'Adams',
      'Parker',
      'Chambers',
      'Graham',
      'Bell',
      'Roberts',
      'Anderson',
      'Khan',
      'Collins',
      'Campbell',
      'Stewart',
      'Reid',
      'Murray',
      'Cook',
      'Palmer',
      'Holmes',
      'Mason',
      'Howard',
      'Fisher',
      'Hunter',
      'Russell',
      'Webb',
      'Simpson',
      'Cox',
      'Harvey',
      'Grant',
      'Spencer',
      'Richardson',
      'Barrett',
      'Shaw',
      'Knight',
      'Owen',
      'Kennedy',
      'Wells',
      'Price',
      'Sanders',
      'Bennett',
      'Mills',
      'Barnes',
      'Foster',
      'Atkinson',
      'Brooks',
      'Long',
      'Ryan',
      'Porter',
      'Pearce',
      'Goodwin',
      'Lawson'
    ],
    Country.China: [
      'Wang',
      'Li',
      'Zhang',
      'Liu',
      'Chen',
      'Yang',
      'Huang',
      'Zhao',
      'Wu',
      'Zhou',
      'Xu',
      'Sun',
      'Ma',
      'Zhu',
      'Hu',
      'Guo',
      'He',
      'Gao',
      'Lin',
      'Luo',
      'Zheng',
      'Tang',
      'Xiao',
      'Deng',
      'Han',
      'Cao',
      'Tian',
      'Jiang',
      'Wang',
      'Qi',
      'Kong',
      'Fan',
      'Dong',
      'Liang',
      'Yu',
      'Fang',
      'Chen',
      'Cheng',
      'Shen',
      'Zhong',
      'Lu',
      'Pang',
      'Cui',
      'Duan',
      'Liu',
      'Zhang',
      'Meng',
      'Li',
      'Wei',
      'Long',
      'Wang',
      'Luo',
      'Feng',
      'Yuan',
      'Huang',
      'Peng',
      'Qin',
      'Lai',
      'Mo',
      'Xie',
      'Song',
      'Gu',
      'Lei',
      'Dong',
      'Pan',
      'Cao',
      'Yang',
      'Zou',
      'Liao',
      'Li',
      'Qiu',
      'Yao',
      'Yin',
      'Tang',
      'Cheng',
      'Shen',
      'Wu',
      'Zhu',
      'Xu',
      'Wang',
      'Feng',
      'Xia',
      'Yu',
      'Mao',
      'Gu',
      'Jiang',
      'Huang',
      'Hao',
      'Zheng',
      'Zhou',
      'Wu',
      'Zhang',
      'Chen',
      'Liu',
      'Li',
      'Wang'
    ],
    Country.Russia: [
      'Ivanov',
      'Petrov',
      'Sidorov',
      'Smirnov',
      'Kuznetsov',
      'Popov',
      'Vasiliev',
      'Mikhailov',
      'Fedorov',
      'Novikov',
      'Morozov',
      'Pavlov',
      'Semenov',
      'Stepanov',
      'Vlasov',
      'Romanov',
      'Leonov',
      'Gavrilov',
      'Danilov',
      'Zakharov',
      'Volkov',
      'Frolov',
      'Korolev',
      'Yakovlev',
      'Belyaev',
      'Bykov',
      'Gusev',
      'Drozdov',
      'Zhukov',
      'Kovalev',
      'Laptev',
      'Maksimov',
      'Nikiforov',
      'Ostrovsky',
      'Polyakov',
      'Rogov',
      'Sergeev',
      'Sorokin',
      'Tikhonov',
      'Uvarov',
      'Filippov',
      'Chernov',
      'Shcherbakov',
      'Shishkin',
      'Yermakov',
      'Yudin',
      'Yushkov',
      'Zakharov',
      'Zaytsev',
      'Zhukov',
      'Andreyev',
      'Belyakov',
      'Bogdanov',
      'Borodin',
      'Dmitriev',
      'Drozdov',
      'Efimov',
      'Erofeev',
      'Fokin',
      'Gerasimov',
      'Gromov',
      'Ivanov',
      'Kalinin',
      'Kovalenko',
      'Kravchenko',
      'Lukyanov',
      'Makarov',
      'Matveev',
      'Mikhailov',
      'Nikonov',
      'Pavlov',
      'Petrov',
      'Polyakov',
      'Popov',
      'Romanov',
      'Smirnov',
      'Sorokin',
      'Sukhanov',
      'Tikhonov',
      'Ulyanov',
      'Volkov',
      'Voronin',
      'Yakovlev',
      'Yermakov',
      'Yudin',
      'Zaytsev',
      'Zhukov',
      'Borisov',
      'Gusev',
      'Sokolov',
      'Petrov',
      'Kozlov',
      'Andreev',
      'Lebedev',
      'Yakovlev',
      'Vorobyev'
    ],
    Country.Brazil: [
      'Silva',
      'Santos',
      'Oliveira',
      'Souza',
      'Rodrigues',
      'Ferreira',
      'Almeida',
      'Pereira',
      'Lima',
      'Gomes',
      'Costa',
      'Ribeiro',
      'Martins',
      'Carvalho',
      'Goncalves',
      'Alves',
      'Marques',
      'Cardoso',
      'Barbosa',
      'Campos',
      'Correia',
      'Pinto',
      'Moura',
      'Nogueira',
      'Teixeira',
      'Araujo',
      'Vieira',
      'Lopes',
      'Nunes',
      'Machado',
      'Fernandes',
      'Ramos',
      'Freitas',
      'Dias',
      'Castro',
      'Vaz',
      'Sousa',
      'Cunha',
      'Monteiro',
      'Azevedo',
      'Simoes',
      'Miranda',
      'Braga',
      'Faria',
      'Rocha',
      'Silveira',
      'Cardoso',
      'Barros',
      'Moreira',
      'Saraiva',
      'Figueiredo',
      'Barbosa',
      'Macedo',
      'Cabral',
      'Maia',
      'Bastos',
      'Amaral',
      'Coelho',
      'Carvalho',
      'Lacerda',
      'Marinho',
      'Esteves',
      'Nascimento',
      'Coutinho',
      'Queiroz',
      'Menezes',
      'Medeiros',
      'Rezende',
      'Melo',
      'Rios',
      'Franco',
      'Fonseca',
      'Martins',
      'Santana',
      'Costa',
      'Ramos',
      'Guedes',
      'Valente',
      'Lopes',
      'Meireles',
      'Barros',
      'Leal',
      'Moura',
      'Sousa',
      'Fernandes',
      'Medeiros',
      'Pinheiro',
      'Castro',
      'Carvalho',
      'Santos',
      'Gomes',
      'Freitas',
      'Rocha',
      'Sousa',
      'Pires',
      'Neves'
    ],
    Country.Canada: [
      'Smith',
      'Brown',
      'Tremblay',
      'Martin',
      'Roy',
      'Wilson',
      'Macdonald',
      'Gagnon',
      'Ouellet',
      'Fournier',
      'Johnson',
      'Williams',
      'Jones',
      'Miller',
      'Davis',
      'Garcia',
      'Martinez',
      'Hernandez',
      'Lopez',
      'Gonzalez',
      'Wilson',
      'Anderson',
      'Thomas',
      'Taylor',
      'Moore',
      'Jackson',
      'Martin',
      'Lee',
      'Perez',
      'Thompson',
      'White',
      'Harris',
      'Sanchez',
      'Clark',
      'Ramirez',
      'Lewis',
      'Robinson',
      'Walker',
      'Young',
      'Allen',
      'King',
      'Wright',
      'Scott',
      'Torres',
      'Nguyen',
      'Hill',
      'Flores',
      'Green',
      'Adams',
      'Nelson',
      'Baker',
      'Hall',
      'Rivera',
      'Campbell',
      'Mitchell',
      'Carter',
      'Roberts',
      'Gomez',
      'Phillips',
      'Evans',
      'Turner',
      'Diaz',
      'Parker',
      'Cruz',
      'Edwards',
      'Collins',
      'Reyes',
      'Stewart',
      'Morris',
      'Morales',
      'Murphy',
      'Cook',
      'Rogers',
      'Gutierrez',
      'Ortiz',
      'Morgan',
      'Cooper',
      'Peterson',
      'Bailey',
      'Reed',
      'Kelly',
      'Howard',
      'Ramos',
      'Kim',
      'Cox',
      'Ward',
      'Richardson',
      'Watson',
      'Brooks',
      'Chavez',
      'Wood',
      'James',
      'Bennett',
      'Gray',
      'Mendoza',
      'Ruiz'
    ],
    Country.Australia: [
      'Smith',
      'Jones',
      'Williams',
      'Brown',
      'Wilson',
      'Taylor',
      'Lee',
      'Harris',
      'Martin',
      'Thompson',
      'White',
      'Walker',
      'Robinson',
      'Wood',
      'Hall',
      'Clark',
      'Allen',
      'Wright',
      'King',
      'Lewis',
      'Scott',
      'Young',
      'Hill',
      'Edwards',
      'Green',
      'Baker',
      'Adams',
      'Campbell',
      'Mitchell',
      'Carter',
      'Phillips',
      'Evans',
      'Turner',
      'Parker',
      'Collins',
      'Morris',
      'Murphy',
      'Cook',
      'Rogers',
      'Morgan',
      'Peterson',
      'Bailey',
      'Reed',
      'Kelly',
      'Howard',
      'Ward',
      'Watson',
      'Brooks',
      'James',
      'Bennett',
      'Gray',
      'Mendoza',
      'Ruiz',
      'Hughes',
      'Price',
      'Alvarez',
      'Castillo',
      'Sanders',
      'Patel',
      'Myers',
      'Long',
      'Ross',
      'Foster',
      'Gutierrez',
      'Ortiz',
      'Morgan',
      'Cooper',
      'Bailey',
      'Watson',
      'Brooks',
      'Rivera',
      'Cox',
      'Ward',
      'Richardson',
      'Wood',
      'Miller',
      'Davis',
      'Garcia',
      'Martinez',
      'Hernandez',
      'Lopez',
      'Gonzalez',
      'Wilson',
      'Anderson',
      'Thomas',
      'Taylor',
      'Moore',
      'Jackson',
      'Martin',
      'Lee'
    ],
    Country.Italy: [
      'Rossi',
      'Russo',
      'Ferrari',
      'Esposito',
      'Bianchi',
      'Romano',
      'Colombo',
      'Ricci',
      'Marino',
      'Greco',
      'Bruno',
      'Gallo',
      'Conti',
      'De Luca',
      'Costa',
      'Giordano',
      'Mancini',
      'Rizzo',
      'Lombardi',
      'Moretti',
      'Barbieri',
      'Fontana',
      'Santoro',
      'Mariani',
      'Rinaldi',
      'Caruso',
      'Ferraro',
      'Galli',
      'Martini',
      'Leone',
      'Longo',
      'Gentile',
      'Martinelli',
      'Vitale',
      'Lombardo',
      'Serra',
      'D\'Angelo',
      'Amato',
      'Sanna',
      'Farina',
      'Ruggiero',
      'Monti',
      'Cattaneo',
      'Mazza',
      'Lupo',
      'Villa',
      'Maggio',
      'Sorrentino',
      'Fiore',
      'Silvestri',
      'Motta',
      'Conti',
      'Valenti',
      'Messina',
      'Marchetti',
      'Sacco',
      'De Rosa',
      'De Santis',
      'Greco',
      'Parisi',
      'Pagano',
      'Benedetti',
      'Morelli',
      'Pellegrini',
      'Ferraro',
      'Coppola',
      'Piras',
      'Ferraro',
      'Montanari',
      'Orlando',
      'Barone',
      'Caruso',
      'Fabbri',
      'Ferretti',
      'Giuliani',
      'Landi',
      'Luciani',
      'Mazza',
      'Montanari',
      'Orlando',
      'Palumbo',
      'Parisi',
      'Riva',
      'Rizzi',
      'Russo',
      'Santoro',
      'Sartori',
      'Satta',
      'Serra',
      'Silvestri',
      'Sorrentino',
      'Testa',
      'Toscano',
      'Valentini',
      'Valle',
      'Villa'
    ],
    Country.Spain: [
      'Garcia',
      'Martinez',
      'Lopez',
      'Sanchez',
      'Perez',
      'Gonzalez',
      'Rodriguez',
      'Fernandez',
      'Martin',
      'Gomez',
      'Ruiz',
      'Diaz',
      'Hernandez',
      'Alvarez',
      'Jimenez',
      'Moreno',
      'Munoz',
      'Alonso',
      'Gutierrez',
      'Navarro',
      'Torres',
      'Dominguez',
      'Vazquez',
      'Ramos',
      'Gil',
      'Ramirez',
      'Serrano',
      'Blanco',
      'Molina',
      'Morales',
      'Ortega',
      'Delgado',
      'Castro',
      'Ortiz',
      'Rubio',
      'Marin',
      'Iglesias',
      'Nunez',
      'Medina',
      'Garrido',
      'Cruz',
      'Herrera',
      'Suarez',
      'Castillo',
      'Santos',
      'Prieto',
      'Hidalgo',
      'Aguilar',
      'Leon',
      'Vega',
      'Franco',
      'Pascual',
      'Cortes',
      'Garcia',
      'Ortiz',
      'Vidal',
      'Benitez',
      'Mendez',
      'Lopez',
      'Martin',
      'Sanchez',
      'Rodriguez',
      'Fernandez',
      'Alvarez',
      'Gomez',
      'Ruiz',
      'Diaz',
      'Hernandez',
      'Jimenez',
      'Moreno',
      'Munoz',
      'Alonso',
      'Gutierrez',
      'Navarro',
      'Torres',
      'Dominguez',
      'Vazquez',
      'Ramos',
      'Gil',
      'Ramirez',
      'Serrano',
      'Blanco',
      'Molina',
      'Morales',
      'Ortega',
      'Delgado',
      'Castro',
      'Ortiz',
      'Rubio',
      'Marin'
    ],
    Country.Mexico: [
      'Hernandez',
      'Garcia',
      'Martinez',
      'Lopez',
      'Gonzalez',
      'Perez',
      'Rodriguez',
      'Sanchez',
      'Ramirez',
      'Cruz',
      'Flores',
      'Gomez',
      'Morales',
      'Hernandez',
      'Ortiz',
      'Gutierrez',
      'Ramos',
      'Romero',
      'Alvarez',
      'Ruiz',
      'Diaz',
      'Torres',
      'Chavez',
      'Vargas',
      'Castillo',
      'Garza',
      'Vasquez',
      'Soto',
      'Aguilar',
      'Munoz',
      'Mendoza',
      'Salinas',
      'Guerrero',
      'Lozano',
      'Rios',
      'Ortega',
      'Pena',
      'Santiago',
      'Estrada',
      'Vega',
      'Rios',
      'Ponce',
      'Campos',
      'Cortez',
      'Bravo',
      'Castro',
      'Silva',
      'Pacheco',
      'Figueroa',
      'Rivera',
      'Hernandez',
      'Garcia',
      'Martinez',
      'Lopez',
      'Gonzalez',
      'Perez',
      'Rodriguez',
      'Sanchez',
      'Ramirez',
      'Cruz',
      'Flores',
      'Gomez',
      'Morales',
      'Hernandez',
      'Ortiz',
      'Gutierrez',
      'Ramos',
      'Romero',
      'Alvarez',
      'Ruiz',
      'Diaz',
      'Torres',
      'Chavez',
      'Vargas',
      'Castillo',
      'Garza',
      'Vasquez',
      'Soto',
      'Aguilar',
      'Munoz',
      'Mendoza',
      'Salinas',
      'Guerrero',
      'Lozano',
      'Rios',
      'Ortega',
      'Pena',
      'Santiago',
      'Estrada',
      'Vega'
    ],
    Country.SouthKorea: [
      'Kim',
      'Lee',
      'Park',
      'Choi',
      'Jung',
      'Kang',
      'Cho',
      'Yoon',
      'Jang',
      'Lim',
      'Han',
      'Shin',
      'Song',
      'Oh',
      'Seo',
      'Yoon',
      'Kwon',
      'Hwang',
      'Yoo',
      'Chung',
      'Hong',
      'Ryu',
      'Koo',
      'Ahn',
      'Nam',
      'Ji',
      'Bae',
      'Joo',
      'Suh',
      'Shin',
      'Moon',
      'Huh',
      'Chae',
      'Sung',
      'Ha',
      'Rhee',
      'Baek',
      'Won',
      'Koh',
      'Noh',
      'Min',
      'Kang',
      'Yim',
      'Heo',
      'Han',
      'Jo',
      'Yoo',
      'Yoo',
      'Go',
      'Song',
      'Oh',
      'Lim',
      'Baek',
      'Jung',
      'Lee',
      'Kim',
      'Park',
      'Choi',
      'Jung',
      'Kang',
      'Cho',
      'Yoon',
      'Jang',
      'Lim',
      'Han',
      'Shin',
      'Song',
      'Oh',
      'Seo',
      'Yoon',
      'Kwon',
      'Hwang',
      'Yoo',
      'Chung',
      'Hong',
      'Ryu',
      'Koo',
      'Ahn',
      'Nam',
      'Ji',
      'Bae',
      'Joo',
      'Suh',
      'Shin',
      'Moon',
      'Huh',
      'Chae',
      'Sung',
      'Ha',
      'Rhee'
    ]
  };

  final List<String> _hobbies = [
    'Reading',
    'Swimming',
    'Cooking',
    'Hiking',
    'Gaming',
    'Traveling',
    'Gardening',
    'Photography',
    'Drawing',
    'Writing',
    'Dancing',
    'Singing',
    'Running',
    'Cycling',
    'Fishing',
    'Knitting',
    'Yoga',
    'Meditation',
    'Surfing',
    'Skating',
    'Skiing',
    'Snowboarding',
    'Basketball',
    'Soccer',
    'Tennis',
    'Badminton',
    'Baseball',
    'Volleyball',
    'Table Tennis',
    'Chess',
    'Puzzles',
    'Board Games',
    'Card Games',
    'Collecting',
    'Bird Watching',
    'Stargazing',
    'Volunteering',
    'DIY Projects',
    'Pottery',
    'Woodworking',
    'Painting',
    'Calligraphy',
    'Scrapbooking',
    'Origami',
    'Martial Arts',
    'Fencing',
    'Archery',
    'Scuba Diving',
    'Skydiving',
    'Paragliding',
    'Rock Climbing',
    'Mountaineering',
    'Horse Riding',
    'Golf',
    'Weightlifting',
    'Pilates',
    'Ballet',
    'Acting',
    'Improv',
    'Stand-up Comedy',
    'Podcasting',
    'Vlogging',
    'Blogging',
    'Jewelry Making',
    'Sewing',
    'Crocheting'
  ];

  List<Person> animeCharacters = [
    Person(
        firstname: 'Naruto',
        lastname: 'Uzumaki',
        age: 17,
        hobbies: ['Ninjutsu', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Ichigo',
        lastname: 'Kurosaki',
        age: 15,
        hobbies: ['Sword Fighting', 'Protecting Friends'],
        country: Country.Japan),
    Person(
        firstname: 'Goku',
        lastname: 'Son',
        age: 37,
        hobbies: ['Martial Arts', 'Eating'],
        country: Country.Japan),
    Person(
        firstname: 'Monkey D.',
        lastname: 'Luffy',
        age: 19,
        hobbies: ['Pirating', 'Adventure'],
        country: Country.Japan),
    Person(
        firstname: 'Sakura',
        lastname: 'Haruno',
        age: 17,
        hobbies: ['Medical Ninjutsu', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Light',
        lastname: 'Yagami',
        age: 17,
        hobbies: ['Solving Puzzles', 'Writing in Death Note'],
        country: Country.Japan),
    Person(
        firstname: 'Edward',
        lastname: 'Elric',
        age: 15,
        hobbies: ['Alchemy', 'Research'],
        country: Country.Japan),
    Person(
        firstname: 'Saitama',
        lastname: '-',
        age: 25,
        hobbies: ['Training', 'Fighting Monsters'],
        country: Country.Japan),
    Person(
        firstname: 'Eren',
        lastname: 'Yeager',
        age: 15,
        hobbies: ['Fighting Titans', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Hinata',
        lastname: 'Hyuga',
        age: 17,
        hobbies: ['Training', 'Ninjutsu'],
        country: Country.Japan),
    Person(
        firstname: 'Gon',
        lastname: 'Freecss',
        age: 12,
        hobbies: ['Hunting', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Killua',
        lastname: 'Zoldyck',
        age: 12,
        hobbies: ['Assassination', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Lelouch',
        lastname: 'Lamperouge',
        age: 17,
        hobbies: ['Chess', 'Rebellion'],
        country: Country.Japan),
    Person(
        firstname: 'Natsu',
        lastname: 'Dragneel',
        age: 18,
        hobbies: ['Fighting', 'Eating'],
        country: Country.Japan),
    Person(
        firstname: 'Lucy',
        lastname: 'Heartfilia',
        age: 17,
        hobbies: ['Celestial Magic', 'Writing'],
        country: Country.Japan),
    Person(
        firstname: 'Mikasa',
        lastname: 'Ackerman',
        age: 15,
        hobbies: ['Fighting Titans', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Kenshin',
        lastname: 'Himura',
        age: 28,
        hobbies: ['Swordsmanship', 'Wandering'],
        country: Country.Japan),
    Person(
        firstname: 'Yusuke',
        lastname: 'Urameshi',
        age: 14,
        hobbies: ['Spirit Detective', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Shinji',
        lastname: 'Ikari',
        age: 14,
        hobbies: ['Piloting Eva', 'Music'],
        country: Country.Japan),
    Person(
        firstname: 'Rin',
        lastname: 'Okumura',
        age: 15,
        hobbies: ['Exorcism', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Tanjiro',
        lastname: 'Kamado',
        age: 15,
        hobbies: ['Demon Slaying', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Nezuko',
        lastname: 'Kamado',
        age: 14,
        hobbies: ['Demon Slaying', 'Sleeping'],
        country: Country.Japan),
    Person(
        firstname: 'Inuyasha',
        lastname: '-',
        age: 200,
        hobbies: ['Demon Hunting', 'Traveling'],
        country: Country.Japan),
    Person(
        firstname: 'Kagome',
        lastname: 'Higurashi',
        age: 15,
        hobbies: ['Archery', 'Traveling'],
        country: Country.Japan),
    Person(
        firstname: 'Sasuke',
        lastname: 'Uchiha',
        age: 17,
        hobbies: ['Ninjutsu', 'Revenge'],
        country: Country.Japan),
    Person(
        firstname: 'Boruto',
        lastname: 'Uzumaki',
        age: 12,
        hobbies: ['Ninjutsu', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'L',
        lastname: 'Lawliet',
        age: 24,
        hobbies: ['Solving Cases', 'Eating Sweets'],
        country: Country.Japan),
    Person(
        firstname: 'Misa',
        lastname: 'Amane',
        age: 19,
        hobbies: ['Modeling', 'Acting'],
        country: Country.Japan),
    Person(
        firstname: 'Winry',
        lastname: 'Rockbell',
        age: 15,
        hobbies: ['Mechanics', 'Helping Friends'],
        country: Country.Japan),
    Person(
        firstname: 'Roy',
        lastname: 'Mustang',
        age: 30,
        hobbies: ['Alchemy', 'Military Strategy'],
        country: Country.Japan),
    Person(
        firstname: 'Asuka',
        lastname: 'Langley',
        age: 14,
        hobbies: ['Piloting Eva', 'Fighting Angels'],
        country: Country.Japan),
    Person(
        firstname: 'Rei',
        lastname: 'Ayanami',
        age: 14,
        hobbies: ['Piloting Eva', 'Reading'],
        country: Country.Japan),
    Person(
        firstname: 'Spike',
        lastname: 'Spiegel',
        age: 27,
        hobbies: ['Bounty Hunting', 'Martial Arts'],
        country: Country.Japan),
    Person(
        firstname: 'Faye',
        lastname: 'Valentine',
        age: 23,
        hobbies: ['Bounty Hunting', 'Gambling'],
        country: Country.Japan),
    Person(
        firstname: 'Vash',
        lastname: 'the Stampede',
        age: 131,
        hobbies: ['Gunslinging', 'Peacekeeping'],
        country: Country.Japan),
    Person(
        firstname: 'Rem',
        lastname: '-',
        age: 17,
        hobbies: ['Housekeeping', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Ram',
        lastname: '-',
        age: 17,
        hobbies: ['Housekeeping', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Subaru',
        lastname: 'Natsuki',
        age: 18,
        hobbies: ['Time Travel', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Emilia',
        lastname: '-',
        age: 100,
        hobbies: ['Magic', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Asta',
        lastname: '-',
        age: 15,
        hobbies: ['Training', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Yuno',
        lastname: '-',
        age: 15,
        hobbies: ['Magic', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Guts',
        lastname: '-',
        age: 24,
        hobbies: ['Sword Fighting', 'Survival'],
        country: Country.Japan),
    Person(
        firstname: 'Griffith',
        lastname: '-',
        age: 24,
        hobbies: ['Leadership', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Shinichi',
        lastname: 'Kudo',
        age: 17,
        hobbies: ['Detective Work', 'Soccer'],
        country: Country.Japan),
    Person(
        firstname: 'Ran',
        lastname: 'Mouri',
        age: 17,
        hobbies: ['Karate', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Conan',
        lastname: 'Edogawa',
        age: 7,
        hobbies: ['Solving Mysteries', 'Soccer'],
        country: Country.Japan),
    Person(
        firstname: 'Nobita',
        lastname: 'Nobi',
        age: 10,
        hobbies: ['Playing', 'Daydreaming'],
        country: Country.Japan),
    Person(
        firstname: 'Doraemon',
        lastname: '-',
        age: 10,
        hobbies: ['Helping Nobita', 'Time Travel'],
        country: Country.Japan),
    Person(
        firstname: 'Shizuka',
        lastname: 'Minamoto',
        age: 10,
        hobbies: ['Playing the Piano', 'Studying'],
        country: Country.Japan),
    Person(
        firstname: 'Suneo',
        lastname: 'Honekawa',
        age: 10,
        hobbies: ['Bragging', 'Playing'],
        country: Country.Japan),
    Person(
        firstname: 'Gian',
        lastname: 'Goda',
        age: 10,
        hobbies: ['Singing', 'Bullying'],
        country: Country.Japan),
    Person(
        firstname: 'Saitou',
        lastname: 'Hajime',
        age: 28,
        hobbies: ['Sword Fighting', 'Police Work'],
        country: Country.Japan),
    Person(
        firstname: 'Shishio',
        lastname: 'Makoto',
        age: 30,
        hobbies: ['Sword Fighting', 'Revolution'],
        country: Country.Japan),
    Person(
        firstname: 'Kaoru',
        lastname: 'Kamiya',
        age: 17,
        hobbies: ['Kendo', 'Teaching'],
        country: Country.Japan),
    Person(
        firstname: 'Tomoe',
        lastname: 'Yukishiro',
        age: 18,
        hobbies: ['Assisting', 'Loving'],
        country: Country.Japan),
    Person(
        firstname: 'Inosuke',
        lastname: 'Hashibira',
        age: 16,
        hobbies: ['Beast Breathing', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Zenitsu',
        lastname: 'Agatsuma',
        age: 16,
        hobbies: ['Thunder Breathing', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Shinobu',
        lastname: 'Kocho',
        age: 18,
        hobbies: ['Insect Breathing', 'Medicine'],
        country: Country.Japan),
    Person(
        firstname: 'Kyojuro',
        lastname: 'Rengoku',
        age: 20,
        hobbies: ['Flame Breathing', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Tomioka',
        lastname: 'Giyu',
        age: 21,
        hobbies: ['Water Breathing', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Muzan',
        lastname: 'Kibutsuji',
        age: 1000,
        hobbies: ['Fighting', 'Evolving'],
        country: Country.Japan),
    Person(
        firstname: 'Kagura',
        lastname: 'Sohma',
        age: 16,
        hobbies: ['Fighting', 'Loving Kyo'],
        country: Country.Japan),
    Person(
        firstname: 'Yuki',
        lastname: 'Sohma',
        age: 16,
        hobbies: ['School Council', 'Helping Tohru'],
        country: Country.Japan),
    Person(
        firstname: 'Kyo',
        lastname: 'Sohma',
        age: 16,
        hobbies: ['Fighting', 'Avoiding Yuki'],
        country: Country.Japan),
    Person(
        firstname: 'Tohru',
        lastname: 'Honda',
        age: 16,
        hobbies: ['Cooking', 'Cleaning'],
        country: Country.Japan),
    Person(
        firstname: 'Hatsuharu',
        lastname: 'Sohma',
        age: 16,
        hobbies: ['Fighting', 'Protecting Tohru'],
        country: Country.Japan),
    Person(
        firstname: 'Shigure',
        lastname: 'Sohma',
        age: 27,
        hobbies: ['Writing', 'Teasing Others'],
        country: Country.Japan),
    Person(
        firstname: 'Hatori',
        lastname: 'Sohma',
        age: 27,
        hobbies: ['Doctoring', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Akito',
        lastname: 'Sohma',
        age: 20,
        hobbies: ['Manipulating', 'Ruling'],
        country: Country.Japan),
    Person(
        firstname: 'Ayame',
        lastname: 'Sohma',
        age: 27,
        hobbies: ['Fashion Designing', 'Teasing Yuki'],
        country: Country.Japan),
    Person(
        firstname: 'Momiji',
        lastname: 'Sohma',
        age: 15,
        hobbies: ['Playing Violin', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Kagome',
        lastname: 'Higurashi',
        age: 15,
        hobbies: ['Archery', 'Helping Inuyasha'],
        country: Country.Japan),
    Person(
        firstname: 'Inuyasha',
        lastname: '-',
        age: 200,
        hobbies: ['Fighting Demons', 'Traveling'],
        country: Country.Japan),
    Person(
        firstname: 'Sesshomaru',
        lastname: '-',
        age: 500,
        hobbies: ['Fighting', 'Protecting Rin'],
        country: Country.Japan),
    Person(
        firstname: 'Kikyo',
        lastname: '-',
        age: 18,
        hobbies: ['Healing', 'Protecting Sacred Jewel'],
        country: Country.Japan),
    Person(
        firstname: 'Miroku',
        lastname: '-',
        age: 20,
        hobbies: ['Exorcism', 'Flirting'],
        country: Country.Japan),
    Person(
        firstname: 'Sango',
        lastname: '-',
        age: 18,
        hobbies: ['Demon Slaying', 'Helping Friends'],
        country: Country.Japan),
    Person(
        firstname: 'Shippo',
        lastname: '-',
        age: 7,
        hobbies: ['Fighting', 'Playing Tricks'],
        country: Country.Japan),
    Person(
        firstname: 'Naraku',
        lastname: '-',
        age: 50,
        hobbies: ['Manipulating', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Kagura',
        lastname: '-',
        age: 20,
        hobbies: ['Wind Manipulation', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Kanna',
        lastname: '-',
        age: 10,
        hobbies: ['Mirror Manipulation', 'Spying'],
        country: Country.Japan),
    Person(
        firstname: 'Ayanami',
        lastname: 'Rei',
        age: 14,
        hobbies: ['Piloting Eva', 'Reading'],
        country: Country.Japan),
    Person(
        firstname: 'Kaworu',
        lastname: 'Nagisa',
        age: 15,
        hobbies: ['Playing Piano', 'Piloting Eva'],
        country: Country.Japan),
    Person(
        firstname: 'Misato',
        lastname: 'Katsuragi',
        age: 29,
        hobbies: ['Drinking Beer', 'Commanding NERV'],
        country: Country.Japan),
    Person(
        firstname: 'Ritsuko',
        lastname: 'Akagi',
        age: 30,
        hobbies: ['Science', 'Working at NERV'],
        country: Country.Japan),
    Person(
        firstname: 'Gendo',
        lastname: 'Ikari',
        age: 48,
        hobbies: ['Leading NERV', 'Manipulating Others'],
        country: Country.Japan),
    Person(
        firstname: 'Yui',
        lastname: 'Ikari',
        age: 30,
        hobbies: ['Science', 'Being a Mother'],
        country: Country.Japan),
    Person(
        firstname: 'Kaji',
        lastname: 'Ryoji',
        age: 30,
        hobbies: ['Spying', 'Farming'],
        country: Country.Japan),
    Person(
        firstname: 'Shinji',
        lastname: 'Ikari',
        age: 14,
        hobbies: ['Piloting Eva', 'Music'],
        country: Country.Japan),
    Person(
        firstname: 'Asuka',
        lastname: 'Langley',
        age: 14,
        hobbies: ['Piloting Eva', 'Fighting Angels'],
        country: Country.Japan),
    Person(
        firstname: 'Homura',
        lastname: 'Akemi',
        age: 14,
        hobbies: ['Time Manipulation', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Madoka',
        lastname: 'Kaname',
        age: 14,
        hobbies: ['Helping Others', 'Being a Magical Girl'],
        country: Country.Japan),
    Person(
        firstname: 'Mami',
        lastname: 'Tomoe',
        age: 15,
        hobbies: ['Tea Drinking', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Sayaka',
        lastname: 'Miki',
        age: 14,
        hobbies: ['Sword Fighting', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Kyoko',
        lastname: 'Sakura',
        age: 15,
        hobbies: ['Eating', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Nagisa',
        lastname: 'Momoe',
        age: 14,
        hobbies: ['Cheesecake Eating', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Rikka',
        lastname: 'Takanashi',
        age: 16,
        hobbies: ['Fantasy Roleplay', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Yuta',
        lastname: 'Togashi',
        age: 16,
        hobbies: ['Taking Care of Rikka', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Shinka',
        lastname: 'Nibutani',
        age: 16,
        hobbies: ['Cheerleading', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Kumin',
        lastname: 'Tsuyuri',
        age: 17,
        hobbies: ['Napping', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Satone',
        lastname: 'Shichimiya',
        age: 16,
        hobbies: ['Fantasy Roleplay', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Tsubasa',
        lastname: 'Hanekawa',
        age: 17,
        hobbies: ['Studying', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Koyomi',
        lastname: 'Araragi',
        age: 18,
        hobbies: ['Helping Others', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Hitagi',
        lastname: 'Senjougahara',
        age: 18,
        hobbies: ['Being Tsundere', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Shinobu',
        lastname: 'Oshino',
        age: 599,
        hobbies: ['Eating Donuts', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Mayoi',
        lastname: 'Hachikuji',
        age: 11,
        hobbies: ['Wandering', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Suruga',
        lastname: 'Kanbaru',
        age: 18,
        hobbies: ['Playing Basketball', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Nadeko',
        lastname: 'Sengoku',
        age: 14,
        hobbies: ['Collecting Snakes', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Sodachi',
        lastname: 'Oikura',
        age: 18,
        hobbies: ['Studying', 'Revenge'],
        country: Country.Japan),
    Person(
        firstname: 'Yotsugi',
        lastname: 'Ononoki',
        age: 12,
        hobbies: ['Playing with Yotsugi', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Karen',
        lastname: 'Araragi',
        age: 16,
        hobbies: ['Martial Arts', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Tsukihi',
        lastname: 'Araragi',
        age: 14,
        hobbies: ['Traditional Dance', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Mikoto',
        lastname: 'Misaka',
        age: 14,
        hobbies: ['Electrokinesis', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Kuroko',
        lastname: 'Shirai',
        age: 14,
        hobbies: ['Teleportation', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Accelerator',
        lastname: '-',
        age: 15,
        hobbies: ['Vector Manipulation', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Touma',
        lastname: 'Kamijou',
        age: 16,
        hobbies: ['Fighting', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Index',
        lastname: 'Librorum',
        age: 14,
        hobbies: ['Reading', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Victor',
        lastname: 'Nikiforov',
        age: 27,
        hobbies: ['Figure Skating', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Yuri',
        lastname: 'Katsuki',
        age: 23,
        hobbies: ['Figure Skating', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Yuri',
        lastname: 'Plisetsky',
        age: 15,
        hobbies: ['Figure Skating', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Phichit',
        lastname: 'Chulanont',
        age: 20,
        hobbies: ['Figure Skating', 'Taking Photos'],
        country: Country.Japan),
    Person(
        firstname: 'Mila',
        lastname: 'Babicheva',
        age: 18,
        hobbies: ['Figure Skating', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Georgi',
        lastname: 'Popovich',
        age: 25,
        hobbies: ['Figure Skating', 'Drama'],
        country: Country.Japan),
    Person(
        firstname: 'Celty',
        lastname: 'Sturluson',
        age: 1000,
        hobbies: ['Riding Motorcycle', 'Searching for Head'],
        country: Country.Japan),
    Person(
        firstname: 'Mikado',
        lastname: 'Ryuugamine',
        age: 17,
        hobbies: ['Internet', 'Leading Dollars'],
        country: Country.Japan),
    Person(
        firstname: 'Anri',
        lastname: 'Sonohara',
        age: 17,
        hobbies: ['Swordsmanship', 'Reading'],
        country: Country.Japan),
    Person(
        firstname: 'Shizuo',
        lastname: 'Heiwajima',
        age: 24,
        hobbies: ['Fighting', 'Throwing Vending Machines'],
        country: Country.Japan),
    Person(
        firstname: 'Izaya',
        lastname: 'Orihara',
        age: 24,
        hobbies: ['Manipulating', 'Information Gathering'],
        country: Country.Japan),
    Person(
        firstname: 'Kasuka',
        lastname: 'Heiwajima',
        age: 22,
        hobbies: ['Acting', 'Avoiding Shizuo'],
        country: Country.Japan),
    Person(
        firstname: 'Simon',
        lastname: 'Breznev',
        age: 29,
        hobbies: ['Sushi Making', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Erika',
        lastname: 'Karisuwa',
        age: 17,
        hobbies: ['Cosplay', 'Fandom'],
        country: Country.Japan),
    Person(
        firstname: 'Walker',
        lastname: 'Yumasaki',
        age: 17,
        hobbies: ['Light Novels', 'Cosplay'],
        country: Country.Japan),
    Person(
        firstname: 'Aoba',
        lastname: 'Kuronuma',
        age: 15,
        hobbies: ['Hacking', 'Manipulation'],
        country: Country.Japan),
    Person(
        firstname: 'Ryu',
        lastname: 'Fudou',
        age: 25,
        hobbies: ['Racing', 'Mechanics'],
        country: Country.Japan),
    Person(
        firstname: 'Rin',
        lastname: 'Matsuoka',
        age: 17,
        hobbies: ['Swimming', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Haruka',
        lastname: 'Nanase',
        age: 17,
        hobbies: ['Swimming', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Makoto',
        lastname: 'Tachibana',
        age: 17,
        hobbies: ['Swimming', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Nagisa',
        lastname: 'Hazuki',
        age: 16,
        hobbies: ['Swimming', 'Being Cheerful'],
        country: Country.Japan),
    Person(
        firstname: 'Rei',
        lastname: 'Ryuugazaki',
        age: 17,
        hobbies: ['Swimming', 'Wearing Glasses'],
        country: Country.Japan),
    Person(
        firstname: 'Sousuke',
        lastname: 'Yamazaki',
        age: 17,
        hobbies: ['Swimming', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Aiichiro',
        lastname: 'Nitori',
        age: 16,
        hobbies: ['Swimming', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Seijuro',
        lastname: 'Mikoshi',
        age: 18,
        hobbies: ['Swimming', 'Leading'],
        country: Country.Japan),
    Person(
        firstname: 'Momotaro',
        lastname: 'Mikoshiba',
        age: 17,
        hobbies: ['Swimming', 'Cheerfulness'],
        country: Country.Japan),
    Person(
        firstname: 'Goro',
        lastname: 'Sakuragi',
        age: 35,
        hobbies: ['Coaching', 'Encouraging'],
        country: Country.Japan),
    Person(
        firstname: 'Sosuke',
        lastname: 'Yamashita',
        age: 18,
        hobbies: ['Swimming', 'Being Stoic'],
        country: Country.Japan),
    Person(
        firstname: 'Ayano',
        lastname: 'Hanesaki',
        age: 17,
        hobbies: ['Badminton', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Nagisa',
        lastname: 'Arisugawa',
        age: 16,
        hobbies: ['Cycling', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Midori',
        lastname: 'Nagatsuki',
        age: 16,
        hobbies: ['Cycling', 'Helping'],
        country: Country.Japan),
    Person(
        firstname: 'Naruko',
        lastname: 'Shoukichi',
        age: 16,
        hobbies: ['Cycling', 'Talking'],
        country: Country.Japan),
    Person(
        firstname: 'Makishima',
        lastname: 'Yuusuke',
        age: 17,
        hobbies: ['Cycling', 'Encouraging'],
        country: Country.Japan),
    Person(
        firstname: 'Shunsuke',
        lastname: 'Imamura',
        age: 17,
        hobbies: ['Cycling', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Yukari',
        lastname: 'Nishiyama',
        age: 17,
        hobbies: ['Cycling', 'Leading'],
        country: Country.Japan),
    Person(
        firstname: 'Onoda',
        lastname: 'Sakamichi',
        age: 16,
        hobbies: ['Cycling', 'Being Enthusiastic'],
        country: Country.Japan),
    Person(
        firstname: 'Arakita',
        lastname: 'Yasutomo',
        age: 18,
        hobbies: ['Cycling', 'Being Tough'],
        country: Country.Japan),
    Person(
        firstname: 'Tadokoro',
        lastname: 'Jin',
        age: 18,
        hobbies: ['Cycling', 'Eating'],
        country: Country.Japan),
    Person(
        firstname: 'Imaizumi',
        lastname: 'Shunsuke',
        age: 17,
        hobbies: ['Cycling', 'Being Focused'],
        country: Country.Japan),
    Person(
        firstname: 'Teshima',
        lastname: 'Junta',
        age: 17,
        hobbies: ['Cycling', 'Strategizing'],
        country: Country.Japan),
    Person(
        firstname: 'Kinjou',
        lastname: 'Shingo',
        age: 18,
        hobbies: ['Cycling', 'Leading'],
        country: Country.Japan),
    Person(
        firstname: 'Midosuji',
        lastname: 'Akira',
        age: 17,
        hobbies: ['Cycling', 'Intimidating'],
        country: Country.Japan),
    Person(
        firstname: 'Kuroda',
        lastname: 'Yukinari',
        age: 17,
        hobbies: ['Cycling', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Nariyuki',
        lastname: 'Yuiga',
        age: 18,
        hobbies: ['Studying', 'Teaching'],
        country: Country.Japan),
    Person(
        firstname: 'Fumino',
        lastname: 'Furuhashi',
        age: 17,
        hobbies: ['Studying', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Rizu',
        lastname: 'Ogata',
        age: 17,
        hobbies: ['Studying', 'Gaming'],
        country: Country.Japan),
    Person(
        firstname: 'Uruka',
        lastname: 'Takemoto',
        age: 17,
        hobbies: ['Swimming', 'Training'],
        country: Country.Japan),
    Person(
        firstname: 'Asumi',
        lastname: 'Kominami',
        age: 18,
        hobbies: ['Studying', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Maika',
        lastname: 'Sakuranomiya',
        age: 16,
        hobbies: ['Serving Customers', 'Cooking'],
        country: Country.Japan),
    Person(
        firstname: 'Kaho',
        lastname: 'Hinata',
        age: 17,
        hobbies: ['Serving Customers', 'Gaming'],
        country: Country.Japan),
    Person(
        firstname: 'Mafuyu',
        lastname: 'Hoshikawa',
        age: 20,
        hobbies: ['Serving Customers', 'Teaching'],
        country: Country.Japan),
    Person(
        firstname: 'Miu',
        lastname: 'Amana',
        age: 18,
        hobbies: ['Serving Customers', 'Writing'],
        country: Country.Japan),
    Person(
        firstname: 'Akizuki',
        lastname: 'Hikari',
        age: 17,
        hobbies: ['Serving Customers', 'Fighting'],
        country: Country.Japan),
    Person(
        firstname: 'Tsundere',
        lastname: 'Miyabi',
        age: 16,
        hobbies: ['Being Tsundere', 'Cooking'],
        country: Country.Japan),
    Person(
        firstname: 'Nana',
        lastname: 'Osaki',
        age: 20,
        hobbies: ['Singing', 'Playing Guitar'],
        country: Country.Japan),
    Person(
        firstname: 'Nana',
        lastname: 'Komatsu',
        age: 20,
        hobbies: ['Shopping', 'Dreaming'],
        country: Country.Japan),
    Person(
        firstname: 'Holo',
        lastname: 'the Wise Wolf',
        age: 600,
        hobbies: ['Trading', 'Eating Apples'],
        country: Country.Japan),
    Person(
        firstname: 'Simon',
        lastname: 'Gurren',
        age: 21,
        hobbies: ['Drilling', 'Exploring'],
        country: Country.Japan),
    Person(
        firstname: 'Yoko',
        lastname: 'Littner',
        age: 24,
        hobbies: ['Shooting', 'Teaching'],
        country: Country.Japan),
    Person(
        firstname: 'Kamina',
        lastname: '-',
        age: 18,
        hobbies: ['Fighting', 'Inspiring'],
        country: Country.Japan),
    Person(
        firstname: 'Makoto',
        lastname: 'Naegi',
        age: 16,
        hobbies: ['Investigating', 'Helping Friends'],
        country: Country.Japan),
    Person(
        firstname: 'Kyoko',
        lastname: 'Kirishima',
        age: 16,
        hobbies: ['Investigating', 'Solving Mysteries'],
        country: Country.Japan),
    Person(
        firstname: 'Izuku',
        lastname: 'Midoriya',
        age: 16,
        hobbies: ['Hero Training', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Ochaco',
        lastname: 'Uraraka',
        age: 16,
        hobbies: ['Hero Training', 'Helping Others'],
        country: Country.Japan),
    Person(
        firstname: 'Shoto',
        lastname: 'Todoroki',
        age: 16,
        hobbies: ['Hero Training', 'Learning'],
        country: Country.Japan),
  ];

  Person generatePerson(Country country) {
    if (!_firstnames.containsKey(country) || !_lastnames.containsKey(country)) {
      throw ArgumentError('Country not supported: $country');
    }

    String firstname =
        _firstnames[country]![_random.nextInt(_firstnames[country]!.length)];
    String lastname =
        _lastnames[country]![_random.nextInt(_lastnames[country]!.length)];
    int age = _random.nextInt(90) + 10; // 10歳から99歳の間でランダムな年齢を生成
    List<String> hobbies = List.generate(
      _random.nextInt(3) + 1, // 1から3の間でランダムな数の趣味を生成
      (_) => _hobbies[_random.nextInt(_hobbies.length)],
    );

    return Person(
        firstname: firstname,
        lastname: lastname,
        age: age,
        hobbies: hobbies,
        country: country);
  }

  List<Person> generatePersons(Country country, int count) {
    return List.generate(count, (_) => generatePerson(country));
  }

  List<Person> generateAllPersons(int count) {
    final realPersons = List.generate(count, (_) {
      Country country = Country.values[_random.nextInt(Country.values.length)];
      return generatePerson(country);
    });

    return (realPersons + animeCharacters)..shuffle();
  }
}
